//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleApp.Services.Client.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserResponse", Namespace="http://www.xyz.com/2016/03/Services/Data")]
    [System.SerializableAttribute()]
    public partial class UserResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string errorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string firstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string lastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int uidField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.errorCodeField, value) != true)) {
                    this.errorCodeField = value;
                    this.RaisePropertyChanged("errorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string firstName {
            get {
                return this.firstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.firstNameField, value) != true)) {
                    this.firstNameField = value;
                    this.RaisePropertyChanged("firstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string lastName {
            get {
                return this.lastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.lastNameField, value) != true)) {
                    this.lastNameField = value;
                    this.RaisePropertyChanged("lastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int uid {
            get {
                return this.uidField;
            }
            set {
                if ((this.uidField.Equals(value) != true)) {
                    this.uidField = value;
                    this.RaisePropertyChanged("uid");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserRequest", Namespace="http://www.xyz.com/2016/03/Services/Data")]
    [System.SerializableAttribute()]
    public partial class UserRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string firstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string lastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int uidField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string firstName {
            get {
                return this.firstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.firstNameField, value) != true)) {
                    this.firstNameField = value;
                    this.RaisePropertyChanged("firstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string lastName {
            get {
                return this.lastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.lastNameField, value) != true)) {
                    this.lastNameField = value;
                    this.RaisePropertyChanged("lastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int uid {
            get {
                return this.uidField;
            }
            set {
                if ((this.uidField.Equals(value) != true)) {
                    this.uidField = value;
                    this.RaisePropertyChanged("uid");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.xyz.com/2016/03/Services", ConfigurationName="ServiceReference1.ISOAPTEMPLATEApi")]
    public interface ISOAPTEMPLATEApi {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.xyz.com/2016/03/Services/ISOAPTEMPLATEApi/GetSOAPHello", ReplyAction="http://www.xyz.com/2016/03/Services/ISOAPTEMPLATEApi/GetSOAPHelloResponse")]
        string GetSOAPHello(string name);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISOAPTEMPLATEApiChannel : SampleApp.Services.Client.ServiceReference1.ISOAPTEMPLATEApi, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SOAPTEMPLATEApiClient : System.ServiceModel.ClientBase<SampleApp.Services.Client.ServiceReference1.ISOAPTEMPLATEApi>, SampleApp.Services.Client.ServiceReference1.ISOAPTEMPLATEApi {
        
        public SOAPTEMPLATEApiClient() {
        }
        
        public SOAPTEMPLATEApiClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SOAPTEMPLATEApiClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SOAPTEMPLATEApiClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SOAPTEMPLATEApiClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetSOAPHello(string name) {
            return base.Channel.GetSOAPHello(name);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.xyz.com/2016/03/Services", ConfigurationName="ServiceReference1.IRESTTEMPLATEInternalApi")]
    public interface IRESTTEMPLATEInternalApi {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.xyz.com/2016/03/Services/IRESTTEMPLATEInternalApi/GetRESTInternalHello" +
            "", ReplyAction="http://www.xyz.com/2016/03/Services/IRESTTEMPLATEInternalApi/GetRESTInternalHello" +
            "Response")]
        string GetRESTInternalHello(string name);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRESTTEMPLATEInternalApiChannel : SampleApp.Services.Client.ServiceReference1.IRESTTEMPLATEInternalApi, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RESTTEMPLATEInternalApiClient : System.ServiceModel.ClientBase<SampleApp.Services.Client.ServiceReference1.IRESTTEMPLATEInternalApi>, SampleApp.Services.Client.ServiceReference1.IRESTTEMPLATEInternalApi {
        
        public RESTTEMPLATEInternalApiClient() {
        }
        
        public RESTTEMPLATEInternalApiClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RESTTEMPLATEInternalApiClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RESTTEMPLATEInternalApiClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RESTTEMPLATEInternalApiClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetRESTInternalHello(string name) {
            return base.Channel.GetRESTInternalHello(name);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.xyz.com/2016/03/Services", ConfigurationName="ServiceReference1.IRESTTEMPLATEExternalApi")]
    public interface IRESTTEMPLATEExternalApi {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.xyz.com/2016/03/Services/IRESTTEMPLATEExternalApi/GetRESTExternalHello" +
            "", ReplyAction="http://www.xyz.com/2016/03/Services/IRESTTEMPLATEExternalApi/GetRESTExternalHello" +
            "Response")]
        string GetRESTExternalHello(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.xyz.com/2016/03/Services/IRESTTEMPLATEExternalApi/GetUsers", ReplyAction="http://www.xyz.com/2016/03/Services/IRESTTEMPLATEExternalApi/GetUsersResponse")]
        System.Collections.Generic.List<SampleApp.Services.Client.ServiceReference1.UserResponse> GetUsers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.xyz.com/2016/03/Services/IRESTTEMPLATEExternalApi/GetPagedUsers", ReplyAction="http://www.xyz.com/2016/03/Services/IRESTTEMPLATEExternalApi/GetPagedUsersRespons" +
            "e")]
        System.Collections.Generic.List<SampleApp.Services.Client.ServiceReference1.UserResponse> GetPagedUsers(string uid, string pageIndex, string pageSize, string filters, string sortColumn, string sortOrder, string active);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.xyz.com/2016/03/Services/IRESTTEMPLATEExternalApi/GetUser", ReplyAction="http://www.xyz.com/2016/03/Services/IRESTTEMPLATEExternalApi/GetUserResponse")]
        SampleApp.Services.Client.ServiceReference1.UserResponse GetUser(string uid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.xyz.com/2016/03/Services/IRESTTEMPLATEExternalApi/SaveUser", ReplyAction="http://www.xyz.com/2016/03/Services/IRESTTEMPLATEExternalApi/SaveUserResponse")]
        SampleApp.Services.Client.ServiceReference1.UserResponse SaveUser(SampleApp.Services.Client.ServiceReference1.UserRequest req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.xyz.com/2016/03/Services/IRESTTEMPLATEExternalApi/DeleteUser", ReplyAction="http://www.xyz.com/2016/03/Services/IRESTTEMPLATEExternalApi/DeleteUserResponse")]
        void DeleteUser(string uid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.xyz.com/2016/03/Services/IRESTTEMPLATEExternalApi/CopyUser", ReplyAction="http://www.xyz.com/2016/03/Services/IRESTTEMPLATEExternalApi/CopyUserResponse")]
        void CopyUser(string uid);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRESTTEMPLATEExternalApiChannel : SampleApp.Services.Client.ServiceReference1.IRESTTEMPLATEExternalApi, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RESTTEMPLATEExternalApiClient : System.ServiceModel.ClientBase<SampleApp.Services.Client.ServiceReference1.IRESTTEMPLATEExternalApi>, SampleApp.Services.Client.ServiceReference1.IRESTTEMPLATEExternalApi {
        
        public RESTTEMPLATEExternalApiClient() {
        }
        
        public RESTTEMPLATEExternalApiClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RESTTEMPLATEExternalApiClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RESTTEMPLATEExternalApiClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RESTTEMPLATEExternalApiClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetRESTExternalHello(string name) {
            return base.Channel.GetRESTExternalHello(name);
        }
        
        public System.Collections.Generic.List<SampleApp.Services.Client.ServiceReference1.UserResponse> GetUsers() {
            return base.Channel.GetUsers();
        }
        
        public System.Collections.Generic.List<SampleApp.Services.Client.ServiceReference1.UserResponse> GetPagedUsers(string uid, string pageIndex, string pageSize, string filters, string sortColumn, string sortOrder, string active) {
            return base.Channel.GetPagedUsers(uid, pageIndex, pageSize, filters, sortColumn, sortOrder, active);
        }
        
        public SampleApp.Services.Client.ServiceReference1.UserResponse GetUser(string uid) {
            return base.Channel.GetUser(uid);
        }
        
        public SampleApp.Services.Client.ServiceReference1.UserResponse SaveUser(SampleApp.Services.Client.ServiceReference1.UserRequest req) {
            return base.Channel.SaveUser(req);
        }
        
        public void DeleteUser(string uid) {
            base.Channel.DeleteUser(uid);
        }
        
        public void CopyUser(string uid) {
            base.Channel.CopyUser(uid);
        }
    }
}
