//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demandtec.DealManagement.Services.Client.Client {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CommonDealPackage", Namespace="http://www.demandtec.com/DM/2012/01/Services/Data")]
    [System.SerializableAttribute()]
    public partial class CommonDealPackage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Demandtec.DealManagement.Services.Client.Client.AllowanceType AllowanceTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> AllowanceTypeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ChangedDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CommonDealIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CommonDealPackageIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreatedDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Demandtec.DealManagement.Services.Client.Client.PackageRelationType PackageRelationTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> PackageRelationTypeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Demandtec.DealManagement.Services.Client.Client.ProductSet PrimaryProductSetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrimaryProductSetBasisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> PrimaryProductSetIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PrimaryProductSetQuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Demandtec.DealManagement.Services.Client.Client.ProductSetRelationType ProductSetRelationTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ProductSetRelationTypeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] RowVersionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SecondaryProductSetBasisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> SecondaryProductSetIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SecondaryProductSetQuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Demandtec.DealManagement.Services.Client.Client.TransactionType TransactionTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> TransactionTypeIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Demandtec.DealManagement.Services.Client.Client.AllowanceType AllowanceType {
            get {
                return this.AllowanceTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.AllowanceTypeField, value) != true)) {
                    this.AllowanceTypeField = value;
                    this.RaisePropertyChanged("AllowanceType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> AllowanceTypeId {
            get {
                return this.AllowanceTypeIdField;
            }
            set {
                if ((this.AllowanceTypeIdField.Equals(value) != true)) {
                    this.AllowanceTypeIdField = value;
                    this.RaisePropertyChanged("AllowanceTypeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ChangedDateTime {
            get {
                return this.ChangedDateTimeField;
            }
            set {
                if ((this.ChangedDateTimeField.Equals(value) != true)) {
                    this.ChangedDateTimeField = value;
                    this.RaisePropertyChanged("ChangedDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CommonDealId {
            get {
                return this.CommonDealIdField;
            }
            set {
                if ((this.CommonDealIdField.Equals(value) != true)) {
                    this.CommonDealIdField = value;
                    this.RaisePropertyChanged("CommonDealId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CommonDealPackageId {
            get {
                return this.CommonDealPackageIdField;
            }
            set {
                if ((this.CommonDealPackageIdField.Equals(value) != true)) {
                    this.CommonDealPackageIdField = value;
                    this.RaisePropertyChanged("CommonDealPackageId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedDateTime {
            get {
                return this.CreatedDateTimeField;
            }
            set {
                if ((this.CreatedDateTimeField.Equals(value) != true)) {
                    this.CreatedDateTimeField = value;
                    this.RaisePropertyChanged("CreatedDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Demandtec.DealManagement.Services.Client.Client.PackageRelationType PackageRelationType {
            get {
                return this.PackageRelationTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.PackageRelationTypeField, value) != true)) {
                    this.PackageRelationTypeField = value;
                    this.RaisePropertyChanged("PackageRelationType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> PackageRelationTypeId {
            get {
                return this.PackageRelationTypeIdField;
            }
            set {
                if ((this.PackageRelationTypeIdField.Equals(value) != true)) {
                    this.PackageRelationTypeIdField = value;
                    this.RaisePropertyChanged("PackageRelationTypeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Demandtec.DealManagement.Services.Client.Client.ProductSet PrimaryProductSet {
            get {
                return this.PrimaryProductSetField;
            }
            set {
                if ((object.ReferenceEquals(this.PrimaryProductSetField, value) != true)) {
                    this.PrimaryProductSetField = value;
                    this.RaisePropertyChanged("PrimaryProductSet");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PrimaryProductSetBasis {
            get {
                return this.PrimaryProductSetBasisField;
            }
            set {
                if ((object.ReferenceEquals(this.PrimaryProductSetBasisField, value) != true)) {
                    this.PrimaryProductSetBasisField = value;
                    this.RaisePropertyChanged("PrimaryProductSetBasis");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> PrimaryProductSetId {
            get {
                return this.PrimaryProductSetIdField;
            }
            set {
                if ((this.PrimaryProductSetIdField.Equals(value) != true)) {
                    this.PrimaryProductSetIdField = value;
                    this.RaisePropertyChanged("PrimaryProductSetId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PrimaryProductSetQuantity {
            get {
                return this.PrimaryProductSetQuantityField;
            }
            set {
                if ((this.PrimaryProductSetQuantityField.Equals(value) != true)) {
                    this.PrimaryProductSetQuantityField = value;
                    this.RaisePropertyChanged("PrimaryProductSetQuantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Demandtec.DealManagement.Services.Client.Client.ProductSetRelationType ProductSetRelationType {
            get {
                return this.ProductSetRelationTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductSetRelationTypeField, value) != true)) {
                    this.ProductSetRelationTypeField = value;
                    this.RaisePropertyChanged("ProductSetRelationType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ProductSetRelationTypeId {
            get {
                return this.ProductSetRelationTypeIdField;
            }
            set {
                if ((this.ProductSetRelationTypeIdField.Equals(value) != true)) {
                    this.ProductSetRelationTypeIdField = value;
                    this.RaisePropertyChanged("ProductSetRelationTypeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] RowVersion {
            get {
                return this.RowVersionField;
            }
            set {
                if ((object.ReferenceEquals(this.RowVersionField, value) != true)) {
                    this.RowVersionField = value;
                    this.RaisePropertyChanged("RowVersion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SecondaryProductSetBasis {
            get {
                return this.SecondaryProductSetBasisField;
            }
            set {
                if ((object.ReferenceEquals(this.SecondaryProductSetBasisField, value) != true)) {
                    this.SecondaryProductSetBasisField = value;
                    this.RaisePropertyChanged("SecondaryProductSetBasis");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> SecondaryProductSetId {
            get {
                return this.SecondaryProductSetIdField;
            }
            set {
                if ((this.SecondaryProductSetIdField.Equals(value) != true)) {
                    this.SecondaryProductSetIdField = value;
                    this.RaisePropertyChanged("SecondaryProductSetId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SecondaryProductSetQuantity {
            get {
                return this.SecondaryProductSetQuantityField;
            }
            set {
                if ((this.SecondaryProductSetQuantityField.Equals(value) != true)) {
                    this.SecondaryProductSetQuantityField = value;
                    this.RaisePropertyChanged("SecondaryProductSetQuantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Demandtec.DealManagement.Services.Client.Client.TransactionType TransactionType {
            get {
                return this.TransactionTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TransactionTypeField, value) != true)) {
                    this.TransactionTypeField = value;
                    this.RaisePropertyChanged("TransactionType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> TransactionTypeId {
            get {
                return this.TransactionTypeIdField;
            }
            set {
                if ((this.TransactionTypeIdField.Equals(value) != true)) {
                    this.TransactionTypeIdField = value;
                    this.RaisePropertyChanged("TransactionTypeId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AllowanceType", Namespace="http://www.demandtec.com/DM/2012/01/Services/Data")]
    [System.SerializableAttribute()]
    public partial class AllowanceType : Demandtec.DealManagement.Services.Client.Client.LookUpEntity {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PackageRelationType", Namespace="http://www.demandtec.com/DM/2012/01/Services/Data")]
    [System.SerializableAttribute()]
    public partial class PackageRelationType : Demandtec.DealManagement.Services.Client.Client.LookUpEntity {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductSet", Namespace="http://www.demandtec.com/DM/2012/01/Services/Data")]
    [System.SerializableAttribute()]
    public partial class ProductSet : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreatedDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductSetIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Demandtec.DealManagement.Services.Client.Client.ProductSetItem[] ProductSetItemsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductSetNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] RowVersionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedDateTime {
            get {
                return this.CreatedDateTimeField;
            }
            set {
                if ((this.CreatedDateTimeField.Equals(value) != true)) {
                    this.CreatedDateTimeField = value;
                    this.RaisePropertyChanged("CreatedDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductSetId {
            get {
                return this.ProductSetIdField;
            }
            set {
                if ((this.ProductSetIdField.Equals(value) != true)) {
                    this.ProductSetIdField = value;
                    this.RaisePropertyChanged("ProductSetId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Demandtec.DealManagement.Services.Client.Client.ProductSetItem[] ProductSetItems {
            get {
                return this.ProductSetItemsField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductSetItemsField, value) != true)) {
                    this.ProductSetItemsField = value;
                    this.RaisePropertyChanged("ProductSetItems");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductSetName {
            get {
                return this.ProductSetNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductSetNameField, value) != true)) {
                    this.ProductSetNameField = value;
                    this.RaisePropertyChanged("ProductSetName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] RowVersion {
            get {
                return this.RowVersionField;
            }
            set {
                if ((object.ReferenceEquals(this.RowVersionField, value) != true)) {
                    this.RowVersionField = value;
                    this.RaisePropertyChanged("RowVersion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductSetRelationType", Namespace="http://www.demandtec.com/DM/2012/01/Services/Data")]
    [System.SerializableAttribute()]
    public partial class ProductSetRelationType : Demandtec.DealManagement.Services.Client.Client.LookUpEntity {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TransactionType", Namespace="http://www.demandtec.com/DM/2012/01/Services/Data")]
    [System.SerializableAttribute()]
    public partial class TransactionType : Demandtec.DealManagement.Services.Client.Client.LookUpEntity {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LookUpEntity", Namespace="http://www.demandtec.com/DM/2012/01/Services/Data")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Demandtec.DealManagement.Services.Client.Client.PackageRelationType))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Demandtec.DealManagement.Services.Client.Client.ProductSetRelationType))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Demandtec.DealManagement.Services.Client.Client.TransactionType))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Demandtec.DealManagement.Services.Client.Client.AllowanceType))]
    public partial class LookUpEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductSetItem", Namespace="http://www.demandtec.com/DM/2012/01/Services/Data")]
    [System.SerializableAttribute()]
    public partial class ProductSetItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreatedDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Demandtec.DealManagement.Services.Client.Client.ProductSet ProductSetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductSetIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Demandtec.DealManagement.Services.Client.Client.RetailItem RetailItemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RetailItemIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] RowVersionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedDateTime {
            get {
                return this.CreatedDateTimeField;
            }
            set {
                if ((this.CreatedDateTimeField.Equals(value) != true)) {
                    this.CreatedDateTimeField = value;
                    this.RaisePropertyChanged("CreatedDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Demandtec.DealManagement.Services.Client.Client.ProductSet ProductSet {
            get {
                return this.ProductSetField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductSetField, value) != true)) {
                    this.ProductSetField = value;
                    this.RaisePropertyChanged("ProductSet");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductSetId {
            get {
                return this.ProductSetIdField;
            }
            set {
                if ((this.ProductSetIdField.Equals(value) != true)) {
                    this.ProductSetIdField = value;
                    this.RaisePropertyChanged("ProductSetId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Demandtec.DealManagement.Services.Client.Client.RetailItem RetailItem {
            get {
                return this.RetailItemField;
            }
            set {
                if ((object.ReferenceEquals(this.RetailItemField, value) != true)) {
                    this.RetailItemField = value;
                    this.RaisePropertyChanged("RetailItem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RetailItemId {
            get {
                return this.RetailItemIdField;
            }
            set {
                if ((this.RetailItemIdField.Equals(value) != true)) {
                    this.RetailItemIdField = value;
                    this.RaisePropertyChanged("RetailItemId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] RowVersion {
            get {
                return this.RowVersionField;
            }
            set {
                if ((object.ReferenceEquals(this.RowVersionField, value) != true)) {
                    this.RowVersionField = value;
                    this.RaisePropertyChanged("RowVersion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RetailItem", Namespace="http://www.demandtec.com/DM/2012/01/Services/Data")]
    [System.SerializableAttribute()]
    public partial class RetailItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ItemDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ItemGroupField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PackSizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RetailItemIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RetailItemNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SellingGroupField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UPCBlockField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UPCCaseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UPCConsumerField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemDescription {
            get {
                return this.ItemDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemDescriptionField, value) != true)) {
                    this.ItemDescriptionField = value;
                    this.RaisePropertyChanged("ItemDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemGroup {
            get {
                return this.ItemGroupField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemGroupField, value) != true)) {
                    this.ItemGroupField = value;
                    this.RaisePropertyChanged("ItemGroup");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PackSize {
            get {
                return this.PackSizeField;
            }
            set {
                if ((object.ReferenceEquals(this.PackSizeField, value) != true)) {
                    this.PackSizeField = value;
                    this.RaisePropertyChanged("PackSize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RetailItemId {
            get {
                return this.RetailItemIdField;
            }
            set {
                if ((this.RetailItemIdField.Equals(value) != true)) {
                    this.RetailItemIdField = value;
                    this.RaisePropertyChanged("RetailItemId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RetailItemNumber {
            get {
                return this.RetailItemNumberField;
            }
            set {
                if ((this.RetailItemNumberField.Equals(value) != true)) {
                    this.RetailItemNumberField = value;
                    this.RaisePropertyChanged("RetailItemNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SellingGroup {
            get {
                return this.SellingGroupField;
            }
            set {
                if ((object.ReferenceEquals(this.SellingGroupField, value) != true)) {
                    this.SellingGroupField = value;
                    this.RaisePropertyChanged("SellingGroup");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UPCBlock {
            get {
                return this.UPCBlockField;
            }
            set {
                if ((object.ReferenceEquals(this.UPCBlockField, value) != true)) {
                    this.UPCBlockField = value;
                    this.RaisePropertyChanged("UPCBlock");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UPCCase {
            get {
                return this.UPCCaseField;
            }
            set {
                if ((object.ReferenceEquals(this.UPCCaseField, value) != true)) {
                    this.UPCCaseField = value;
                    this.RaisePropertyChanged("UPCCase");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UPCConsumer {
            get {
                return this.UPCConsumerField;
            }
            set {
                if ((object.ReferenceEquals(this.UPCConsumerField, value) != true)) {
                    this.UPCConsumerField = value;
                    this.RaisePropertyChanged("UPCConsumer");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.demandtec.com/DM/2012/01/Services", ConfigurationName="Client.Deals")]
    public interface Deals {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.demandtec.com/DM/2012/01/Services/Packages/GetPackages", ReplyAction="http://www.demandtec.com/DM/2012/01/Services/Packages/GetPackagesResponse")]
        Demandtec.DealManagement.Services.Client.Client.CommonDealPackage[] GetPackages(int commonDealId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.demandtec.com/DM/2012/01/Services/Packages/SavePackages", ReplyAction="http://www.demandtec.com/DM/2012/01/Services/Packages/SavePackagesResponse")]
        void SavePackages(Demandtec.DealManagement.Services.Client.Client.CommonDealPackage[] commonDealPackages);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.demandtec.com/DM/2012/01/Services/Packages/ValidatePackageDeal", ReplyAction="http://www.demandtec.com/DM/2012/01/Services/Packages/ValidatePackageDealResponse" +
            "")]
        void ValidatePackageDeal(Demandtec.DealManagement.Services.Client.Client.CommonDealPackage[] commonDealPackages);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.demandtec.com/DM/2012/01/Services/Packages/DeletePackage", ReplyAction="http://www.demandtec.com/DM/2012/01/Services/Packages/DeletePackageResponse")]
        void DeletePackage(int commonDealPackageId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.demandtec.com/DM/2012/01/Services/Packages/GetAllPromotionType", ReplyAction="http://www.demandtec.com/DM/2012/01/Services/Packages/GetAllPromotionTypeResponse" +
            "")]
        void GetAllPromotionType();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.demandtec.com/DM/2012/01/Services/Packages/IsProductSetNameAvailable", ReplyAction="http://www.demandtec.com/DM/2012/01/Services/Packages/IsProductSetNameAvailableRe" +
            "sponse")]
        bool IsProductSetNameAvailable(int commonDealId, string productSetName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.demandtec.com/DM/2012/01/Services/Packages/CreateOrUpdateProductSet", ReplyAction="http://www.demandtec.com/DM/2012/01/Services/Packages/CreateOrUpdateProductSetRes" +
            "ponse")]
        Demandtec.DealManagement.Services.Client.Client.ProductSet CreateOrUpdateProductSet(int commonDealId, Demandtec.DealManagement.Services.Client.Client.ProductSet productSet);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.demandtec.com/DM/2012/01/Services/Deals/GetDeals", ReplyAction="http://www.demandtec.com/DM/2012/01/Services/Deals/GetDealsResponse")]
        string GetDeals(int value);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DealsChannel : Demandtec.DealManagement.Services.Client.Client.Deals, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DealsClient : System.ServiceModel.ClientBase<Demandtec.DealManagement.Services.Client.Client.Deals>, Demandtec.DealManagement.Services.Client.Client.Deals {
        
        public DealsClient() {
        }
        
        public DealsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DealsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DealsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DealsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Demandtec.DealManagement.Services.Client.Client.CommonDealPackage[] GetPackages(int commonDealId) {
            return base.Channel.GetPackages(commonDealId);
        }
        
        public void SavePackages(Demandtec.DealManagement.Services.Client.Client.CommonDealPackage[] commonDealPackages) {
            base.Channel.SavePackages(commonDealPackages);
        }
        
        public void ValidatePackageDeal(Demandtec.DealManagement.Services.Client.Client.CommonDealPackage[] commonDealPackages) {
            base.Channel.ValidatePackageDeal(commonDealPackages);
        }
        
        public void DeletePackage(int commonDealPackageId) {
            base.Channel.DeletePackage(commonDealPackageId);
        }
        
        public void GetAllPromotionType() {
            base.Channel.GetAllPromotionType();
        }
        
        public bool IsProductSetNameAvailable(int commonDealId, string productSetName) {
            return base.Channel.IsProductSetNameAvailable(commonDealId, productSetName);
        }
        
        public Demandtec.DealManagement.Services.Client.Client.ProductSet CreateOrUpdateProductSet(int commonDealId, Demandtec.DealManagement.Services.Client.Client.ProductSet productSet) {
            return base.Channel.CreateOrUpdateProductSet(commonDealId, productSet);
        }
        
        public string GetDeals(int value) {
            return base.Channel.GetDeals(value);
        }
    }
}
